const multiLib=require("multi-lib2/wrapper");
const bulletMill=multiLib.extend(GenericCrafter,"bullet-mill",
[
  {
    input:{
      items:["lead/2","coal/1"],
      power:0.5
    },
    output:{
      items:["steam-power-bullet/2"]
    },
  },
  {
    input:{
      items:["steam-power-steel/1","pyratite/1","titanium/1"],
      power:1
    },
    output:{
      items:["steam-power-armor-piercing-shell/2"]
    },
    craftTime:90
  },
  {
    input:{
      items:["lead/2","steam-power-iron/1","pyratite/2"],
      power:1
    },
    output:{
      items:["steam-power-cluster-bullet/2"]
    },
    craftTime:90
  },
  {
    input:{
      items:["lead/1","steam-power-iron/1","blast-compound/1"],
      power:1
    },
    output:{
      items:["steam-power-high-explosive/2"]
    },
    craftTime:90
  },
],{},{});
bulletMill.dumpToggle=false;
