const multiLib=require("multi-lib2/wrapper");
const semiconductorPlant=multiLib.extend(GenericCrafter,"semiconductor-plant",
[
  {
    input:{
      items:["lead/2","silicon/1"],
      power:1,
    },
    output:{
      items:["steam-power-circuit/1"]
    },
    craftTime:120,
  },
  {
    input:{
      items:["silicon/1","graphite/1","plastanium/1"],
      power:3,
    },
    output:{
      items:["steam-power-semiconductor/1"]
    },
    craftTime:120,
  },
  {
    input:{
      items:["steam-power-semiconductor/1","steam-power-circuit/1","surge-alloy/1"],
      power:9,
    },
    output:{
      items:["steam-power-computer/1"]
    },
    craftTime:240,
  },
],{},{});
semiconductorPlant.dumpToggle=true;
